name: flutter_asset_manager

author_name: Usama Azad
email: usamaazad2@gmail.com

description: A command-line tool which auto generates asset directories and register them in pubspec.yaml

version: 0.0.2

homepage: https://github.com/Usama-Azad/flutter_asset_manager
repository: https://github.com/Usama-Azad/flutter_asset_manager
issue_tracker: https://github.com/Usama-Azad/flutter_asset_manager/issues?q=is%3Aissue+is%3Aopen

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

executables:
  assetX: flutter_asset_manager
